const config = {
    urls : {
        api_url: 'http://localhost:9000',
        auth_path: '/auth/web/login',
        add_siteuser_path: '/api/web/addsiteuser',
        edit_siteuser_path: '/api/web/editsiteuser',
        get_siteuser_path: '/api/web/getsiteusers',
        delete_siteuser_path: '/api/web/deletesiteuser',
        add_language_path: '/api/web/addlanguage',
        edit_language_path: '/api/web/editlanguage',
        get_language_path: '/api/web/getlanguages',
        delete_language_path: '/api/web/deletelanguage',
        get_default_countries_path: '/api/web/getdefaultcountries',
        get_country_path: '/api/web/getcountries',
        add_country_path: '/api/web/addcountry',
        edit_country_path: '/api/web/editcountry',
        delete_country_path: '/api/web/deletecountry',
        img_country_path: '/data/countries',
        get_product_path: '/api/web/getproducts',
        add_product_path: '/api/web/addproduct',
        edit_product_path: '/api/web/editproduct',
        delete_product_path: '/api/web/deleteproduct',
        add_product_localize_path: '/api/web/addproductlocalize',
        get_product_localize_path: '/api/web/getproductlocalize',
        edit_product_localize_path: '/api/web/editproductlocalize',
        post_product_image_path: '/api/upload_product_images',
        get_category_path: '/api/web/getcategories',
        get_slide_image_path: '/api/web/getslideimages',
        add_slide_image_path: '/api/web/addslideimage',
        post_slide_image_path: '/api/upload_slide_images',
        delete_slide_image_path: '/api/web/deleteslideimage',
        change_slide_seq_path: '/api/web/changeslideseq',
        get_app_words_path: '/api/web/getappwords',
        add_app_word_path: '/api/web/addappword',
        edit_app_word_path: '/api/web/editappword',
        delete_app_word_path: '/api/web/deleteappword',
        get_app_localize_path: '/api/web/getapplocalize',
        add_app_localize_path: '/api/web/addapplocalize',
        delete_app_localize_path: '/api/web/deleteapplocalize',
        edit_app_localize_path: '/api/web/editapplocalize',
        add_product_price_path: '/api/web/addproductprice',
        edit_product_price_path: '/api/web/editproductprice',
        get_product_price_path: '/api/web/getproductprices',
        delete_product_price_path: '/api/web/deleteproductprice',
        get_product_price_byid_path: '/api/web/getproductprice',
        get_product_byid_path: '/api/web/getproduct',
        get_country_byid_path: '/api/web/getcountry',
        get_language_byid_path: '/api/web/getlanguage',
        get_mobile_user_path: '/api/web/getmobileusers',
        get_product_count_path: '/api/web/getproductcount',
        delete_mobile_user_path: '/api/web/deletemobileuser',
        add_config_path: '/api/web/addconfig',
        edit_config_path: '/api/web/editconfig',
        get_config_path: '/api/web/getconfigs',
        get_config_byid_path: '/api/web/getconfig',
        delete_config_path: '/api/web/deleteconfig',
        get_product_subscribe_path: '/api/web/getproductsubscribe'
    }
}

export default config;